### ISSUE TITLE
HTTP Headers

### ISSUE THREAD

**Issue by JensDollenbacher** [ma-ha/rest-web-ui#11]
Hi Ma-Ha,

Is it possible to set custom HTTP headers for the REST calls?
It would be great if this would be possible.

Thanks
Jens

**Comment by ma-ha** [comment]
Hi Jens
Did you try to use custom headers via definition: request=„header“ 
(pong-form views)?
Doch 
https://github.com/ma-ha/rest-web-ui/blob/master/html/modules/pong-form/README.md
You can combine it with hidden fields option.
Greetings
Markus

-----Original-Nachricht-----
Von: JensDollenbacher <notifications@github.com
<mailto:notifications@github.com> >
Betreff: [ma-ha/rest-web-ui] HTTP Headers (#11)
Datum: 04.06.2018, 21:17 Uhr
An: ma-ha/rest-web-ui <rest-web-ui@noreply.github.com
<mailto:rest-web-ui@noreply.github.com> >
CC: Subscribed <subscribed@noreply.github.com
<mailto:subscribed@noreply.github.com> >

Hi Ma-Ha,

Is it possible to set custom HTTP headers for the REST calls?
It would be great if this would be possible.

Thanks
Jens

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ma-ha/rest-web-ui/issues/11> , or mute the thread

**Comment by JensDollenbacher** [comment]
Hi Markus,
Works perfectly!
Thanks
Jens
